spring.application.name=saree
# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/saree
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ===============================
# = SERVER (Optional)
# ===============================
server.port=8080

razorpay.key.id=rzp_test_SrTm3yYhWpqjzk
razorpay.key.secret=tzL20a9RnXBizfPjRo22nsTn