spring.application.name=saree

# ===============================
# = DATA SOURCE
# ===============================

spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:50788/railway
spring.datasource.username=root
spring.datasource.password=DKgaakueBqfDcMcHlePlmSegojczLqAq
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# = SERVER
# ===============================

server.port=8080

# ===============================
# = RAZORPAY
# ===============================

razorpay.key.id=rzp_test_SrTm3yYhWpqjzk
razorpay.key.secret=tzL20a9RnXBizfPjRo22nsTn